### ISSUE TITLE
annotations ?

### ISSUE THREAD

**Issue by ichiriac** [togajs/tunic#2]
Hi @shannonmoeller,

Do you plan to implement annotations parsing, something similar to this [annotation-parser](https://www.npmjs.com/package/annotation-parser) ?

It could be a great feature :+1:

**Comment by shannonmoeller** [comment]
My goal for tunic is to parse [documentation](https://github.com/togajs/doctree). Currently, I consider annotations to be code and therefore out of scope. I'd have to think about a way to get rudimentary support with a new tagStyle, if at all.

https://github.com/togajs/tunic/blob/v3/src/tagStyles.js

**Comment by ichiriac** [comment]
Thanks for your reply,

You are right, annotations are mainly for code generators, but I need them in my project.

With regex it may be hard to extract all the nested data. FYI I've made a basic SLR parser (quick & dirty) for that https://github.com/glayzzle/php-reflection/blob/master/src/comment.js#L219 / so it's no more necessary

And a sample annotation comments here :
https://github.com/glayzzle/php-reflection/blob/master/test/workspaces/samples/test.php#L18

**Comment by shannonmoeller** [comment]
Agreed about the nesting and regex. Your additional parsing of the ast is exactly what I'd hope to see layered on top. Okay to close this issue?

**Comment by ichiriac** [comment]
Yep, it's closed for me.

BTW, thanks for sharing this lib, I like it's simplicity :+1:
